In [2]:
import pandas as pd
import pulp

Reading the combined file

In [3]:
combined_pd = pd.read_csv('C:/Users/Arwa/Desktop/datasets/jobs_and_freelancers_combined_raw.csv')

Display summary of fields

In [4]:
combined_pd.dtypes

Unnamed: 0                                                  int64
Freelancer_Name                                            object
Freelancer_username                                        object
Freelancer_Average_rating_for_all_completed_projects_x    float64
Freelancer_total_number_of_reviews_x                       object
Budget 1                                                   object
Budget 2                                                   object
Budget 3                                                  float64
Required_Skills 1                                          object
Required_Skills 2                                          object
Required_Skills 3                                          object
Required_Skills 4                                          object
Required_Skills 5                                          object
job_Status                                                 object
Job_url                                                    object
average_employer_rating_by_freelancers                    float64
Job_Budget                                                 object
wage                                                        int64
Freelancer_Average_rating_for_all_completed_projects_y    float64
job_completion_rate                                       float64
Freelancer_title                                           object
on_budget_rate                                            float64
on_time_rate                                              float64
repeat_hire_rate                                          float64
Freelancer_total_number_of_reviews_y                       object
Freelancer_location                                        object
Freelancer_education                                       object
skilks 1                                                   object
skilks 2                                                   object
skilks 3                                                   object
skilks 4                                                   object
skilks 5                                                   object
skilks 6                                                   object
skilks 7                                                   object
skilks 8                                                   object
skilks 9                                                   object
skilks 10                                                  object
dtype: object

Selecting records that have budget in us dollars

In [5]:
#combined_pd_copy = combined_pd.copy()
#data = combined_pd_copy.loc[combined_pd_copy['Job_Budget'] == "$"]
#print(data)

Slice 10 records

In [ ]:
data = combined_pd[0:10].copy()

data['Job_Budget']=15
data['Job_Budget']

In [12]:
data.dtypes

Unnamed: 0                                                  int64
Freelancer_Name                                            object
Freelancer_username                                        object
Freelancer_Average_rating_for_all_completed_projects_x    float64
Freelancer_total_number_of_reviews_x                       object
Budget 1                                                   object
Budget 2                                                   object
Budget 3                                                  float64
Required_Skills 1                                          object
Required_Skills 2                                          object
Required_Skills 3                                          object
Required_Skills 4                                          object
Required_Skills 5                                          object
job_Status                                                 object
Job_url                                                    object
average_employer_rating_by_freelancers                    float64
Job_Budget                                                  int64
wage                                                        int64
Freelancer_Average_rating_for_all_completed_projects_y    float64
job_completion_rate                                       float64
Freelancer_title                                           object
on_budget_rate                                            float64
on_time_rate                                              float64
repeat_hire_rate                                          float64
Freelancer_total_number_of_reviews_y                       object
Freelancer_location                                        object
Freelancer_education                                       object
skilks 1                                                   object
skilks 2                                                   object
skilks 3                                                   object
skilks 4                                                   object
skilks 5                                                   object
skilks 6                                                   object
skilks 7                                                   object
skilks 8                                                   object
skilks 9                                                   object
skilks 10                                                  object
dtype: object


Tasks Set

In [13]:
# takes only tasks 
tasks = data[['Job_url','Job_Budget','Required_Skills 1','Required_Skills 2',
             'Required_Skills 3','Required_Skills 4','Required_Skills 5',
              'Freelancer_Average_rating_for_all_completed_projects_y']].copy()

tasks

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Job_url</th>
      <th>Job_Budget</th>
      <th>Required_Skills 1</th>
      <th>Required_Skills 2</th>
      <th>Required_Skills 3</th>
      <th>Required_Skills 4</th>
      <th>Required_Skills 5</th>
      <th>Freelancer_Average_rating_for_all_completed_projects_y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Banner Design</td>
      <td>Graphic Design</td>
      <td>Logo Design</td>
      <td>Photoshop</td>
      <td>Website Design</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>1</th>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Graphic Design</td>
      <td>Illstrator</td>
      <td>Logo Design</td>
      <td>Photoshop</td>
      <td>NaN</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>2</th>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Graphic Design</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>3</th>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Banner Design</td>
      <td>Graphic Design</td>
      <td>Photoshop</td>
      <td>Prestashop</td>
      <td>Website Design</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>4</th>
      <td>https://www.freelancer.in/projects/Graphic-Des...</td>
      <td>15</td>
      <td>Graphic Design</td>
      <td>Illstrator</td>
      <td>Logo Design</td>
      <td>Photoshop</td>
      <td>Website Design</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>5</th>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Banner Design</td>
      <td>Graphic Design</td>
      <td>Illstrator</td>
      <td>Logo Design</td>
      <td>Website Design</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>6</th>
      <td>https://www.freelancer.in/projects/Linux/Desen...</td>
      <td>15</td>
      <td>Asterisk PBX</td>
      <td>Linx</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>https://www.freelancer.in/projects/network-adm...</td>
      <td>15</td>
      <td>Cisco</td>
      <td>Network Administration</td>
      <td>OpenVMS</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>https://www.freelancer.in/projects/network-adm...</td>
      <td>15</td>
      <td>Compter Secrity</td>
      <td>Network Administration</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>https://www.freelancer.in/projects/php/AHx-Rou...</td>
      <td>15</td>
      <td>Cisco</td>
      <td>Engineering</td>
      <td>Javascript</td>
      <td>PHP</td>
      <td>Web Secrity</td>
      <td>5.0</td>
    </tr>
  </tbody>
</table>
</div>

Workers Set

In [20]:
# takes only workers 
workers = data[['Freelancer_username','wage','skilks 1','skilks 2','skilks 3','skilks 4','skilks 5','skilks 6','skilks 7','skilks 8','skilks 9','skilks 10',
                'on_budget_rate','on_time_rate','repeat_hire_rate','job_completion_rate']].copy()

workers= workers.drop_duplicates()
workers

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Freelancer_username</th>
      <th>wage</th>
      <th>skilks 1</th>
      <th>skilks 2</th>
      <th>skilks 3</th>
      <th>skilks 4</th>
      <th>skilks 5</th>
      <th>skilks 6</th>
      <th>skilks 7</th>
      <th>skilks 8</th>
      <th>skilks 9</th>
      <th>skilks 10</th>
      <th>on_budget_rate</th>
      <th>on_time_rate</th>
      <th>repeat_hire_rate</th>
      <th>job_completion_rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>@AaRTMART</td>
      <td>20</td>
      <td>Graphic Design</td>
      <td>Logo Design</td>
      <td>Illustrator</td>
      <td>Banner Design</td>
      <td>Website Design</td>
      <td>User Interface / IA</td>
      <td>Illustration</td>
      <td>Corporate Identity</td>
      <td>PHP</td>
      <td>Java</td>
      <td>0.97</td>
      <td>0.97</td>
      <td>0.17</td>
      <td>0.98</td>
    </tr>
    <tr>
      <th>6</th>
      <td>@AbrahamBU</td>
      <td>17</td>
      <td>VoIP</td>
      <td>Network Administration</td>
      <td>Asterisk PBX</td>
      <td>Linux</td>
      <td>System Admin</td>
      <td>Cisco</td>
      <td>Web Security</td>
      <td>Wireless</td>
      <td>Computer Security</td>
      <td>Technical Support</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.13</td>
      <td>0.96</td>
    </tr>
  </tbody>
</table>
</div>

Objective Function: 
//////////////////////

we calculate a task value for each incoming task.

The task value is associated with the estimated 
accuracy, skill fitness and cost of the task. The task value is calculated as a weighted linear combination of estimated accuracy, 
skill fitness (higher is better) and cost (lower is better).

Create Worker-Task-Values DataFrame

In [19]:
values = pd.DataFrame(index=(workers['Freelancer_username'],tasks['Job_url']))
values

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>[@AaRTMART, @AbrahamBU]</th>
    </tr>
    <tr>
      <th>[https://www.freelancer.in/projects/graphic-design/banners-design-for-website/, https://www.freelancer.in/projects/graphic-design/Design-Logo-15456935/, https://www.freelancer.in/projects/graphic-design/Design-Medal-15463914/, https://www.freelancer.in/projects/graphic-design/Make-banners-for-prestashoptheme/, https://www.freelancer.in/projects/Graphic-Design/Project-for-AaRTMART-14188509/, https://www.freelancer.in/projects/graphic-design/Project-for-Muhammad-Usman-15428049/, https://www.freelancer.in/projects/Linux/Desenvolver-Software-12019740/, https://www.freelancer.in/projects/network-administration/Mikrotik-Router-Configuration/, https://www.freelancer.in/projects/network-administration/provide-step-step-software-VPN/, https://www.freelancer.in/projects/php/AHx-Routerboard-first-Time-Hotspot/]</th>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
from GetWorkerEstimatedAccuracy import get_worker_estimated_accuracy
from SkillFitnessFunction import skill_fitness_function

instantiate a problem class, we’ll name it “LP_Optimization_Problem” and we’re looking for an optimal maximum so we use LpMaximize

In [25]:
LP_Optimization_Problem = pulp.LpProblem("LP Optimization Problem", pulp.LpMaximize)

 Model our decision variables using the LpVariable class